CMan/CMan/urls.py
from CMan import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('campus/', include("campus.urls", namespace="campus")),
    path('cartriges/', include("cartriges.urls", namespace="cartriges")),
    path('devices/', include("devices.urls", namespace="devices")),
    path('operations/', include("operations.urls", namespace="operations")),
    path('', include("cartriges.urls")), # Временное решение, переадресация пока нет "главной"
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

CMan/cartriges/urls.py
from django.urls import path

from cartriges.views import CartrigesListView, CartrigeDetailView

app_name="cartriges"


urlpatterns = [
    path('', CartrigesListView.as_view(), name="index"),
    path('<slug:cartrige_slug>/', CartrigeDetailView.as_view(), name="detail"),
    ]

CMan/devices/urls.py
from django.urls import path

from devices.views import PrinterListView, UsablePrinterDetailView, UsablePrinterEditView

app_name="devices"


urlpatterns = [

    path('', PrinterListView.as_view(), name="printers"),
    path('use/<int:inv_number>/', UsablePrinterDetailView.as_view(), name="usable_printers"),
    path('use/<int:inv_number>/edit/', UsablePrinterEditView.as_view(), name="usable_printers_edit"),
]

CMan/cartriges/models.py
from django.db import models

from devices.models import Printer


class Cartrige(models.Model):
    CATEGORY_CHOICE = {
        "cartrige":"Картридж",
        "drum":"Барабан",
    }

    name = models.CharField(max_length=256, unique=True, verbose_name="Модель")
    slug = models.SlugField(max_length=256, unique=True, verbose_name="URL")
    amount = models.PositiveSmallIntegerField(default=0, verbose_name="Количество")
    printer = models.ManyToManyField(to=Printer, verbose_name="Совместимость")
    category = models.CharField(max_length=8, choices=CATEGORY_CHOICE, verbose_name="Тип расходника")

    class Meta:
        db_table = "cartriges"
        default_related_name = "cartriges"
        verbose_name = "картридж"
        verbose_name_plural = "картриджи"
        ordering = ("category", "name",)
    
    def __str__(self):
        return f"{self.name} | {self.amount} - {self.category}"

CMan/cartriges/views.py
from django.db.models import Prefetch
from django.views.generic import ListView, DetailView


from cartriges.models import Cartrige
from devices.models import UsablePrinter


class CartrigesListView(ListView):
    model = Cartrige
    context_object_name = "cartriges"


class CartrigeDetailView(DetailView):
    model = Cartrige
    context_object_name = "cartrige"
    slug_url_kwarg="cartrige_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        printers = self.object.printer.all()
        # printers = self.object.printer.prefetch_related(  # Проверить на большой базе = сколько их будет дальше
        #     'usableprinter_set__cabinet'
        # )
        usable_printers = UsablePrinter.objects.filter(printer_id__in=printers)

        context['devices'] = usable_printers

        return context

CMan/templates/cartriges/cartrige_detail.html
{% extends "base.html" %}


{% block content %}
<p>... тут информация по конкретному картриджу ... </p>
    <p>{{cartrige.name}} - {{cartrige.amount}} шт. </p>
    <br>

    <p>Совместимые принтеры:<br>
    Используемые на площадке (по-умолчанию) | в организации | все</p>

    
    <ul> 
        {% for device in devices %}
            <li>
                <a href="{% url "devices:usable_printers" device.inv_number %}">
                    кабинет: {{device.cabinet.name}} | 
                    {{device.printer.name}} - 
                    {{device.inv_number}}
                    - {{device.status}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

CMan/templates/cartriges/cartrige_list.html
{% extends "base.html" %}


{% block content %}
    <p>... тут список картриджей в виде таблицы ... </p>
    <p> [ Картриджи ] | [ Барабаны ] ------ # Добавить фильтры</p>

    <table border="1">
        <thead>
            <tr>
                <th>Категория</th>
                <th>Модель</th>
                <th>Количество</th>
            </tr>
        </thead>
        <tbody>
            {% for cartrige in cartriges %}
                <tr>
                    <td>{{cartrige.category}}</td>
                    <td><a href="{% url "cartriges:detail" cartrige.slug %}">{{cartrige.name}}</a></td>
                    <td>{{cartrige.amount}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

CMan/templates/cartriges/printer_detail.html
{% extends "base.html" %}


{% block content %}
    <p>{{printer.name}}</p>
    <p>{{printer.amount}}</p>
    <br>

    <p>Совместимые расхрдники:</p>
    <ul> 
        {% for cartrige in cartriges %}
            <li>
                <a href="#">{{cartrige.name}} = {{cartrige.amount}} шт.</a>
            </li>
        {% endfor %}
    </ul>    
{% endblock content %}

CMan/templates/cartriges/printer_list.html
{% extends "base.html" %}


{% block content %}
    <p>... тут список принтеров ... </p>

    <ul>
    {% for printer in printers %}
        <li>
            <a href="{% url "cartriges:printers" printer.pk %}">{{printer.name}}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}