CMan/CMan/urls.py
from CMan import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('campus/', include("campus.urls", namespace="campus")),
    path('cartriges/', include("cartriges.urls", namespace="cartriges")),
    path('devices/', include("devices.urls", namespace="devices")),
    path('operations/', include("operations.urls", namespace="operations")),
    path('', include("cartriges.urls")), # Временное решение, переадресация пока нет "главной"
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

CMan/campus/urls.py
from django.urls import path

from campus.views import CampusListView, CampusCabinetView

app_name="campus"


urlpatterns = [
    path('', CampusListView.as_view(), name="index"),
    path('<int:cabinet_pk>/', CampusCabinetView.as_view(), name="cabinet"),

]

CMan/devices/urls.py
from django.urls import path

from devices.views import PrinterListView, UsablePrinterDetailView, UsablePrinterEditView

app_name="devices"


urlpatterns = [

    path('', PrinterListView.as_view(), name="printers"),
    path('use/<int:inv_number>/', UsablePrinterDetailView.as_view(), name="usable_printers"),
    path('use/<int:inv_number>/edit/', UsablePrinterEditView.as_view(), name="usable_printers_edit"),
]

CMan/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Менеджер катриджей</title>
</head>
<body>
    <nav>
        <a href="{% url "cartriges:index" %}">Главная</a>
        <a href="{% url "cartriges:index" %}">Расходники</a>
        <a href="{% url "campus:index" %}">Площадка</a>
        <a href="{% url "devices:printers" %}">Оборудование</a>
        <a href="{% url "operations:index" %}">Аналитика</a>
    </nav>
    {% block content %}
    
    {% endblock content %}
</body>
</html>