CMan/CMan/urls.py
from CMan import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('campus/', include("campus.urls", namespace="campus")),
    path('cartriges/', include("cartriges.urls", namespace="cartriges")),
    path('devices/', include("devices.urls", namespace="devices")),
    path('operations/', include("operations.urls", namespace="operations")),
    path('', include("cartriges.urls")), # Временное решение, переадресация пока нет "главной"
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

CMan/campus/urls.py
from django.urls import path

from campus.views import CampusListView, CampusCabinetView

app_name="campus"


urlpatterns = [
    path('', CampusListView.as_view(), name="index"),
    path('<int:cabinet_pk>/', CampusCabinetView.as_view(), name="cabinet"),

]

CMan/cartriges/urls.py
from django.urls import path

from cartriges.views import CartrigesListView, CartrigeDetailView

app_name="cartriges"


urlpatterns = [
    path('', CartrigesListView.as_view(), name="index"),
    path('<slug:cartrige_slug>/', CartrigeDetailView.as_view(), name="detail"),
    ]

CMan/devices/urls.py
from django.urls import path

from devices.views import PrinterListView, UsablePrinterDetailView, UsablePrinterEditView

app_name="devices"


urlpatterns = [

    path('', PrinterListView.as_view(), name="printers"),
    path('use/<int:inv_number>/', UsablePrinterDetailView.as_view(), name="usable_printers"),
    path('use/<int:inv_number>/edit/', UsablePrinterEditView.as_view(), name="usable_printers_edit"),
]

CMan/operations/urls.py
from django.urls import path

from operations.views import (
    OperationsListView,
    OperationsAddView,
    OperationsRemoveView,
)

app_name = "operations"


urlpatterns = [
    path("", OperationsListView.as_view(), name="index"),
    path("add/", OperationsAddView.as_view(), name="add"),
    path("add/<int:inv_number>", OperationsAddView.as_view(), name="add_from_device"),
    path("add/<slug:cartrige_slug>", OperationsAddView.as_view(), name="add_from_cartrige"), # удалить вместе в вьюшкой
    path("<int:operation_id>/remove/", OperationsRemoveView.as_view(), name="remove"),
]

CMan/devices/models.py
from django.db import models

from campus.models import Cabinet


class Printer(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name="Модель")
    
    class Meta:
        db_table = "printers"
        verbose_name = "принтер"
        verbose_name_plural = "принтеры"
        ordering = ("name",)
    
    def __str__(self):
        return self.name


class UsablePrinter(models.Model):
    PRINTER_STATUS = {
        "working": "Исправен",
        "broken": "Сломан",
    }
    
    cabinet = models.ForeignKey(to=Cabinet, on_delete=models.PROTECT, verbose_name="кабинет")
    printer = models.ForeignKey(to=Printer, on_delete=models.PROTECT, verbose_name="принтер")
    inv_number = models.PositiveSmallIntegerField(unique=True, verbose_name="инвентаризационный номер")
    serial_number = models.CharField(max_length=30, unique=True, blank=True, null=True, verbose_name="серийный номер")
    status = models.CharField(max_length=8, choices=PRINTER_STATUS, verbose_name="Состояние")
    comment = models.TextField(max_length=256, blank=True,  null=True, verbose_name="комментарий")

    ip_adress = models.CharField(max_length=15, unique=True, blank=True, null=True, verbose_name="IP адрес устройства")# create validators 
    host_name = models.CharField(max_length=10, blank=True, null=True, verbose_name="Имя хоста в сети") 

    class Meta:
        db_table="usable_printers"
        default_related_name="usable_printers"
        verbose_name="используемый принтер"
        verbose_name_plural="используемые принтеры"
        ordering=("-status", "cabinet__name",)

    def __str__(self):
        return f"{self.cabinet.name} | {self.printer.name} | {self.inv_number} "

CMan/devices/forms.py
from django.forms import ModelForm

from devices.models import UsablePrinter

class UsablePrinterForm(ModelForm): #форма по изменению данных о конкретном принтере (перенос в другое помещение)
    class Meta:
        model = UsablePrinter
        fields = ""

CMan/devices/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView

from cartriges.models import Printer
from devices.models import UsablePrinter


class PrinterListView(ListView):
    model=UsablePrinter
    context_object_name = "printers"


class UsablePrinterDetailView(DetailView):
    context_object_name = "device"
    pk_url_kwarg = "inv_number"

    def get_object(self, queryset = None):
        return UsablePrinter.objects.get(
            inv_number=self.kwargs.get(self.pk_url_kwarg)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cartriges'] = self.get_object().printer.cartriges.all()
        return context


class UsablePrinterEditView(UpdateView):
    model = UsablePrinter
    fields = '__all__'
    success_url = reverse_lazy("devices:usable_printers")

CMan/templates/devices/printer_detail.html
{% extends "base.html" %}


{% block content %}
<p>... тут информация по виду принтеров ... </p>
    <p>{{printer.name}}</p>
    <p>{{printer.amount}}</p>
    <br>
        <p>Используемые принтеры этой модели:</p>
    <ul> 
        {% for device in devices %}
            <li>
                <a href="{% url "devices:usable_printers" device.inv_number %}">
                    кабинет: {{device.cabinet.name}} устройство: {{device.inv_number}} - {{device.status}}
                </a>
            </li>
        {% endfor %}
    </ul>    
    
    <p>Совместимые расходники:</p>
    <ul> 
        {% for cartrige in cartriges %}
            <li>
                <a href="{% url "cartriges:detail" cartrige.slug %}">
                    {{cartrige.name}} = {{cartrige.amount}} шт.
                </a>
            </li>
        {% endfor %}
    </ul>    
{% endblock content %}

CMan/templates/devices/usableprinter_detail.html
{% extends "base.html" %}


{% block content %}
    <p>... тут информация по конкретному принтеру ... </p>
    <p>### Это должна быть интерактивная форма, чтобы можно было управлять данными ###</p>
<br>   
    <h2>{{device.printer.name}} 
        {% if device.serial_number %}
        - cерийный номер {{device.serial_number}}
        {% endif %}
    </h2>
    <p>Кабинет: <a href="{% url "campus:cabinet" device.cabinet.pk %}" >{{device.cabinet.name}}</a></p>
    <p>Инвентаризационный номер: {{device.inv_number}}</p>
    <p>Состояние: {{device.status}}</p>

<br>
    <p>Состояние расходников:<br>
        Тонер: 89% |
        Барабан: 77%
    </p>

<br>
    <p>Сетевые настройки:<br>
    {% if device.ip_adress %}IP: {{device.ip_adress}}<br>{% endif %}
    {% if device.host_name %}HOST: {{device.host_name}}<br>{% endif %}
    <br>
    {% if device.comment %}Комментарий: {{device.comment}}{% endif %}</p>
    <br>
    <div>
        <a href="{% url "devices:usable_printers_edit" device.inv_number %}">
            <button>Изменить</button>
        </a>
        <a href="{% url "operations:add_from_device" device.inv_number%}">
            <button>Заменить расходники</button>
        </a>
    </div>

    <p>Совместимые расходники:
        <ul> 
            {% for cartrige in cartriges %}
            <li>
                <a href="{% url "cartriges:detail" cartrige.slug %}">
                    {{cartrige.name}} = {{cartrige.amount}} шт.
                </a>
            </li>
            {% endfor %}
        </ul>    
    </p>
        
    
{% endblock content %}

CMan/templates/devices/usableprinter_list.html
{% extends "base.html" %}


{% block content %}
    <p>... тут список принтеров ... </p>

    <ul>
    {% for printer in printers %}
        <li>
            <a href="{% url "devices:usable_printers" printer.inv_number %}">
                кабинет: {{printer.cabinet.name}} 
                устройство: {{printer.inv_number}} 
                - {{printer.status}}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}